from __future__ import annotations

from typing import Protocol
from uuid import UUID

from app.models import Item, User


class UserRepository(Protocol):
    def get_by_email(self, email: str) -> User | None: ...

    def get(self, user_id: UUID) -> User | None: ...

    def list(self, *, skip: int = 0, limit: int = 100) -> tuple[list[User], int]: ...

    def create(self, user: User) -> User: ...

    def update(self, user: User) -> User: ...

    def delete(self, *, user_id: UUID, cascade_items: bool = True) -> None: ...

    def list_all(self) -> list[User]: ...


class ItemRepository(Protocol):
    def get(self, item_id: UUID) -> Item | None: ...

    def list(self, *, skip: int = 0, limit: int = 100) -> tuple[list[Item], int]: ...

    def list_by_owner(
        self, *, owner_id: UUID, skip: int = 0, limit: int = 100
    ) -> tuple[list[Item], int]: ...

    def create(self, item: Item) -> Item: ...

    def update(self, item: Item) -> Item: ...

    def delete(self, *, item_id: UUID) -> None: ...

    def delete_by_owner(self, *, owner_id: UUID) -> int: ...

    def list_all(self) -> list[Item]: ...
